import { IContract } from "../store/types";

export const contracts: IContract[] = [
	{
		text: `HUOBI: BTC (Current Week)`,
		name: `HUOBI:BTC_CW`,
		underlying: `BTC`,
		exchange: `HUOBI`,
		formatter: 2,
	},
	{
		text: `HUOBI: BTC (Next Week)`,
		name: `HUOBI:BTC_NW`,
		underlying: `BTC`,
		exchange: `HUOBI`,
		formatter: 2,
	},
	{
		text: `HUOBI: BTC (Current Quarter)`,
		name: `HUOBI:BTC_CQ`,
		underlying: `BTC`,
		exchange: `HUOBI`,
		formatter: 2,
	},
	{
		text: `HUOBI: ETC (Current Week)`,
		name: `HUOBI:ETC_CW`,
		underlying: `ETC`,
		exchange: `HUOBI`,
		formatter: 3,
	},
	{
		text: `HUOBI: ETC (Next Week)`,
		name: `HUOBI:ETC_NW`,
		underlying: `ETC`,
		exchange: `HUOBI`,
		formatter: 3,
	},
	{
		text: `HUOBI: ETC (Current Quarter)`,
		name: `HUOBI:ETC_CQ`,
		underlying: `ETC`,
		exchange: `HUOBI`,
		formatter: 3,
	},
	{
		text: `HUOBI: ETH (Current Week)`,
		name: `HUOBI:ETH_CW`,
		underlying: `ETH`,
		exchange: `HUOBI`,
		formatter: 3,
	},
	{
		text: `HUOBI: ETH (Next Week)`,
		name: `HUOBI:ETH_NW`,
		underlying: `ETH`,
		exchange: `HUOBI`,
		formatter: 3,
	},
	{
		text: `HUOBI: ETH (Current Quarter)`,
		name: `HUOBI:ETH_CQ`,
		underlying: `ETH`,
		exchange: `HUOBI`,
		formatter: 3,
	},
	{
		text: `HUOBI: EOS (Current Week)`,
		name: `HUOBI:EOS_CW`,
		underlying: `EOS`,
		exchange: `HUOBI`,
		formatter: 3,
	},
	{
		text: `HUOBI: EOS (Next Week)`,
		name: `HUOBI:EOS_NW`,
		underlying: `EOS`,
		exchange: `HUOBI`,
		formatter: 3,
	},
	{
		text: `HUOBI: EOS (Current Quarter)`,
		name: `HUOBI:EOS_CQ`,
		underlying: `EOS`,
		exchange: `HUOBI`,
		formatter: 3,
	},
	{
		text: `HUOBI: LTC (Current Week)`,
		name: `HUOBI:LTC_CW`,
		underlying: `LTC`,
		exchange: `HUOBI`,
		formatter: 3,
	},
	{
		text: `HUOBI: LTC (Next Week)`,
		name: `HUOBI:LTC_NW`,
		underlying: `LTC`,
		exchange: `HUOBI`,
		formatter: 3,
	},
	{
		text: `HUOBI: LTC (Current Quarter)`,
		name: `HUOBI:LTC_CQ`,
		underlying: `LTC`,
		exchange: `HUOBI`,
		formatter: 3,
	},
	{
		text: `HUOBI: BCH (Current Week)`,
		name: `HUOBI:BCH_CW`,
		underlying: `BCH`,
		exchange: `HUOBI`,
		formatter: 3,
	},
	{
		text: `HUOBI: BCH (Next Week)`,
		name: `HUOBI:BCH_NW`,
		underlying: `BCH`,
		exchange: `HUOBI`,
		formatter: 3,
	},
	{
		text: `HUOBI: BCH (Current Quarter)`,
		name: `HUOBI:BCH_CQ`,
		underlying: `BCH`,
		exchange: `HUOBI`,
		formatter: 3,
	},
	{
		text: `HUOBI: XRP (Current Week)`,
		name: `HUOBI:XRP_CW`,
		underlying: `XRP`,
		exchange: `HUOBI`,
		formatter: 4,
	},
	{
		text: `HUOBI: XRP (Next Week)`,
		name: `HUOBI:XRP_NW`,
		underlying: `XRP`,
		exchange: `HUOBI`,
		formatter: 4,
	},
	{
		text: `HUOBI: XRP (Current Quarter)`,
		name: `HUOBI:XRP_CQ`,
		underlying: `XRP`,
		exchange: `HUOBI`,
		formatter: 4,
	},
	{
		text: `HUOBI: TRX (Current Week)`,
		name: `HUOBI:TRX_CW`,
		underlying: `TRX`,
		exchange: `HUOBI`,
		formatter: 5,
	},
	{
		text: `HUOBI: TRX (Next Week)`,
		name: `HUOBI:TRX_NW`,
		underlying: `TRX`,
		exchange: `HUOBI`,
		formatter: 5,
	},
	{
		text: `HUOBI: TRX (Current Quarter)`,
		name: `HUOBI:TRX_CQ`,
		underlying: `TRX`,
		exchange: `HUOBI`,
		formatter: 5,
	},
	{
		text: `HUOBI: BSV (Current Week)`,
		name: `HUOBI:BSV_CW`,
		underlying: `BSV`,
		exchange: `HUOBI`,
		formatter: 3,
	},
	{
		text: `HUOBI: BSV (Next Week)`,
		name: `HUOBI:BSV_NW`,
		underlying: `BSV`,
		exchange: `HUOBI`,
		formatter: 3,
	},
	{
		text: `HUOBI: BSV (Current Quarter)`,
		name: `HUOBI:BSV_CQ`,
		underlying: `BSV`,
		exchange: `HUOBI`,
		formatter: 3,
	},
];

export const chartPeriods = [
	{
		name: "M1",
		text: "1 min",
	},
	{
		name: "M5",
		text: "5 min",
	},
	{
		name: "M15",
		text: "15 min",
	},
	{
		name: "M30",
		text: "30 min",
	},
	{
		name: "H1",
		text: "1 hour",
	},
	{
		name: "H4",
		text: "4 hours",
	},
	{
		name: "D1",
		text: "1 day",
	},
];