import { IContract } from "../store/types";

export enum Underlying {
    'BTC' = 'BTC',
    'ETC' = 'ETC',
    'ETH' = 'ETH',
    'EOS' = 'EOS',
    'LTC' = 'LTC',
    'BCH' = 'BCH',
    'XRP' = 'XRP',
    'TRX' = 'TRX',
    'BSV' = 'BSV',
}

export enum Exchange {
    'HUOBI' = 'HUOBI',
    'BINANCE' = 'BINANCE',
}

export const contracts: IContract[] = [
    {
        text: `HUOBI: BTC (Current Week)`,
        name: `HUOBI:BTC_CW`,
        underlying: Underlying.BTC,
        exchange: Exchange.HUOBI,
        formatter: 2,
    },
    {
        text: `HUOBI: BTC (Next Week)`,
        name: `HUOBI:BTC_NW`,
		underlying: Underlying.BTC,
		exchange: Exchange.HUOBI,
        formatter: 2,
    },
    {
        text: `HUOBI: BTC (Current Quarter)`,
        name: `HUOBI:BTC_CQ`,
		underlying: Underlying.BTC,
		exchange: Exchange.HUOBI,
        formatter: 2,
    },
    {
        text: `HUOBI: ETC (Current Week)`,
        name: `HUOBI:ETC_CW`,
		underlying: Underlying.ETC,
		exchange: Exchange.HUOBI,
        formatter: 3,
    },
    {
        text: `HUOBI: ETC (Next Week)`,
        name: `HUOBI:ETC_NW`,
		underlying: Underlying.ETC,
		exchange: Exchange.HUOBI,
        formatter: 3,
    },
    {
        text: `HUOBI: ETC (Current Quarter)`,
        name: `HUOBI:ETC_CQ`,
		underlying: Underlying.ETC,
		exchange: Exchange.HUOBI,
        formatter: 3,
    },
    {
        text: `HUOBI: ETH (Current Week)`,
        name: `HUOBI:ETH_CW`,
		underlying: Underlying.ETH,
		exchange: Exchange.HUOBI,
        formatter: 3,
    },
    {
        text: `HUOBI: ETH (Next Week)`,
        name: `HUOBI:ETH_NW`,
		underlying: Underlying.ETH,
		exchange: Exchange.HUOBI,
        formatter: 3,
    },
    {
        text: `HUOBI: ETH (Current Quarter)`,
        name: `HUOBI:ETH_CQ`,
		underlying: Underlying.ETH,
		exchange: Exchange.HUOBI,
        formatter: 3,
    },
    {
        text: `HUOBI: EOS (Current Week)`,
        name: `HUOBI:EOS_CW`,
		underlying: Underlying.EOS,
		exchange: Exchange.HUOBI,
        formatter: 3,
    },
    {
        text: `HUOBI: EOS (Next Week)`,
        name: `HUOBI:EOS_NW`,
		underlying: Underlying.EOS,
		exchange: Exchange.HUOBI,
        formatter: 3,
    },
    {
        text: `HUOBI: EOS (Current Quarter)`,
        name: `HUOBI:EOS_CQ`,
		underlying: Underlying.EOS,
		exchange: Exchange.HUOBI,
        formatter: 3,
    },
    {
        text: `HUOBI: LTC (Current Week)`,
        name: `HUOBI:LTC_CW`,
		underlying: Underlying.LTC,
		exchange: Exchange.HUOBI,
        formatter: 3,
    },
    {
        text: `HUOBI: LTC (Next Week)`,
        name: `HUOBI:LTC_NW`,
		underlying: Underlying.LTC,
		exchange: Exchange.HUOBI,
        formatter: 3,
    },
    {
        text: `HUOBI: LTC (Current Quarter)`,
        name: `HUOBI:LTC_CQ`,
		underlying: Underlying.LTC,
		exchange: Exchange.HUOBI,
        formatter: 3,
    },
    {
        text: `HUOBI: BCH (Current Week)`,
        name: `HUOBI:BCH_CW`,
		underlying: Underlying.BCH,
		exchange: Exchange.HUOBI,
        formatter: 3,
    },
    {
        text: `HUOBI: BCH (Next Week)`,
        name: `HUOBI:BCH_NW`,
		underlying: Underlying.BCH,
		exchange: Exchange.HUOBI,
        formatter: 3,
    },
    {
        text: `HUOBI: BCH (Current Quarter)`,
        name: `HUOBI:BCH_CQ`,
		underlying: Underlying.BCH,
		exchange: Exchange.HUOBI,
        formatter: 3,
    },
    {
        text: `HUOBI: XRP (Current Week)`,
        name: `HUOBI:XRP_CW`,
		underlying: Underlying.XRP,
		exchange: Exchange.HUOBI,
        formatter: 4,
    },
    {
        text: `HUOBI: XRP (Next Week)`,
        name: `HUOBI:XRP_NW`,
		underlying: Underlying.XRP,
		exchange: Exchange.HUOBI,
        formatter: 4,
    },
    {
        text: `HUOBI: XRP (Current Quarter)`,
        name: `HUOBI:XRP_CQ`,
		underlying: Underlying.XRP,
		exchange: Exchange.HUOBI,
        formatter: 4,
    },
    {
        text: `HUOBI: TRX (Current Week)`,
        name: `HUOBI:TRX_CW`,
		underlying: Underlying.TRX,
		exchange: Exchange.HUOBI,
        formatter: 5,
    },
    {
        text: `HUOBI: TRX (Next Week)`,
        name: `HUOBI:TRX_NW`,
		underlying: Underlying.TRX,
		exchange: Exchange.HUOBI,
        formatter: 5,
    },
    {
        text: `HUOBI: TRX (Current Quarter)`,
        name: `HUOBI:TRX_CQ`,
		underlying: Underlying.TRX,
		exchange: Exchange.HUOBI,
        formatter: 5,
    },
    {
        text: `HUOBI: BSV (Current Week)`,
        name: `HUOBI:BSV_CW`,
		underlying: Underlying.BSV,
		exchange: Exchange.HUOBI,
        formatter: 3,
    },
    {
        text: `HUOBI: BSV (Next Week)`,
        name: `HUOBI:BSV_NW`,
		underlying: Underlying.BSV,
		exchange: Exchange.HUOBI,
        formatter: 3,
    },
    {
        text: `HUOBI: BSV (Current Quarter)`,
        name: `HUOBI:BSV_CQ`,
		underlying: Underlying.BSV,
		exchange: Exchange.HUOBI,
        formatter: 3,
    },
];

export const chartPeriods = [
    {
        name: "M1",
        text: "1 min",
    },
    {
        name: "M5",
        text: "5 min",
    },
    {
        name: "M15",
        text: "15 min",
    },
    {
        name: "M30",
        text: "30 min",
    },
    {
        name: "H1",
        text: "1 hour",
    },
    {
        name: "H4",
        text: "4 hours",
    },
    {
        name: "D1",
        text: "1 day",
    },
];
